name: Automated API Tests
on: [push, workflow_dispatch] # Run on each push, adding button "Run workflow"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman Tests
        run: |
          newman run "mockapi.io.postman_collection.json" \
            -e "mockapi.io.postman_environment.json" \
            --env-var "base_url=${{ secrets.BASE_URL }}" \
            --reporters cli
